---
go_latest_version: 1.21.6
home: "{{ lookup('env', 'HOME') }}"
local_bin_path: "{{ ansible_env.HOME }}/.local/bin"
blueprint_config_file: "{{ lookup('env','HOME') }}/.blueprint/config.yaml"
blueprint_config_file_exists: "{{ lookup('fileglob', blueprint_config_file) | length > 0 }}"

dev_container: true

common_cargo_packages:
  - fd-find
  - ripgrep
  - git-delta
  - bat
  - bottom

common_pip_packages:
  - pip
  - docker
  - setuptools
  - pynacl
  - aiohttp
  - typer
  - pyyaml
  - pytest
  - hcloud
  - pydo
  - azure-core
  - boto3
  - pandas
  - artifacts-keyring
  - pipx
  - pytest-cov
  - pydantic
  - pydantic[email]

common_pipx_packages:
  - cookiecutter
  - azure-cli
  - uv
  - ruff
  - pre-commit
  - mypy
  - ansible-lint
  - git-review # needed by Zuul
  - yamllint
  - pylint
  - podman-compose
  - yubikey-manager
  - black
  - coverage
  - poetry
  - sphinx
  - poethepoet
  - yt-dlp

common_gem_packages:
  - bundler

common_node_packages:
  - npm
  - prettier
  - nodemon
  - concurrently
  - tsx
  - bash-language-server
  - '@anthropic-ai/claude-code'
  - '@github/copilot'

common_go_packages:
  - github.com/tomnomnom/gron@latest
  - github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  # - github.com/junegunn/fzf@latest # Not supported
  - github.com/sclevine/yj@latest
  # - github.com/opentofu/opentofu/cmd/tofu@latest # Not supported
  - github.com/gokcehan/lf@latest
  - github.com/zyedidia/eget@latest
  - github.com/digitalocean/doctl/cmd/doctl@latest
  - golang.org/x/tools/cmd/godoc@latest
  - github.com/go-delve/delve/cmd/dlv@latest

eget_packages:
  - name: cli/cli
    archs:
      windows: -a zip -f **/*.exe
      debian: -a tar.gz
      darwin: -a zip
  - name: gohugoio/hugo
    archs:
      windows: -a extended -a zip
      debian: -a extended -a tar.gz -a withdeploy
      darwin: -a extended -a tar.gz -a withdeploy
  - name: hetznercloud/cli
    archs:
      windows: -f hcloud
      debian: -f hcloud
      darwin: -f hcloud
  # - name: evgnomon/zygote
  #   archs:
  #     windows: -a ^core
  #     debian: -a ^core
  #     darwin: -a ^core
  #   to: z
  - name: terraform-linters/tflint
    to: tflint
  - name: containers/gvisor-tap-vsock
    to: gvproxy
  - name: block/goose

debian_go_packages:

darwin_go_packages:

common_git_repos:
  - url: https://github.com/alacritty/alacritty.git
    prefix: &prefix_home_src "{{ ansible_env.HOME }}/src"
  - url: ssh://git@github.com/evgnomon/blueprint.git
    prefix: *prefix_home_src
  - url: ssh://git@github.com/evgnomon/zygote.git
    prefix: *prefix_home_src
