---
go_latest_version: 1.21.6
local_bin_path: "{{ ansible_env.HOME }}/.local/bin"
blueprint_config_file: "{{ lookup('env','HOME') }}/.blueprint/config.yaml"

common_cargo_packages:
  - fd-find
  - ripgrep
  - git-delta
  - bat
  - bottom

common_pip_packages:
  - pip
  - docker
  - setuptools
  - git-review # needed by Zuul
  - ansible-lint # check Ansible changes before commit
  - yamllint # Yaml issues exposed in Coc vim
  - pre-commit
  - pylint
  - podman-compose
  - yubikey-manager
  - black
  - pynacl
  - coverage
  - ruff
  - ruff-lsp
  - poetry
  - orjson
  - aiohttp
  - typer
  - pyyaml
  - mypy
  - pytest
  - sphinx
  - poethepoet
  - furo
  - hcloud
  - pandas
  - yt-dlp

common_gem_packages:
  - solargraph
  - bundler
  - rails

common_node_packages:
  - serve
  - npm
  - prettier
  - nodemon

common_go_packages:
  - github.com/tomnomnom/gron@latest
  - github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  # - github.com/junegunn/fzf@latest # Not supported
  - github.com/sclevine/yj@latest
  # - github.com/opentofu/opentofu/cmd/tofu@latest # Not supported
  - github.com/gokcehan/lf@latest
  - github.com/zyedidia/eget@latest
  - github.com/digitalocean/doctl/cmd/doctl@latest

eget_packages:
  - name: cli/cli
    archs:
      windows: -a zip -f **/*.exe
      debian: -a tar.gz
      darwin: -a zip

  - name: gohugoio/hugo
    archs:
      windows: -a extended -a zip
      debian: -a extended -a tar.gz -a withdeploy
      darwin: -a extended -a tar.gz -a withdeploy

  - name: hetznercloud/cli
    archs:
      windows: -f hcloud
      debian: -f hcloud
      darwin: -f hcloud

debian_go_packages:

darwin_go_packages:

common_git_repos:
  - url: https://github.com/alacritty/alacritty.git
    prefix: &prefix_home_src "{{ ansible_env.HOME }}/src"
  - url: ssh://git@github.com/evgnomon/blueprint.git
    prefix: *prefix_home_src
  - url: ssh://git@github.com/evgnomon/zygote.git
    prefix: *prefix_home_src
