---
go_latest_version: 1.21.6
local_bin_path: "{{ ansible_env.HOME }}/.local/bin"
blueprint_config_file: "{{ lookup('env','HOME') }}/.blueprint/config.yaml"

common_cargo_packages:
  - fd-find
  - ripgrep
  - git-delta
  - bat

common_pip_packages:
  - pip
  - docker
  - setuptools
  - git-review  # needed by Zuul
  - ansible-lint  # check Ansible changes before commit
  - yamllint  # Yaml issues exposed in Coc vim
  - pre-commit
  - pylint
  - podman-compose
  - yubikey-manager
  - black
  - pynacl

common_node_packages:
  - serve
  - npm
  - prettier
  - nodemon

common_go_packages:
  - github.com/tomnomnom/gron@latest
  - github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  # - github.com/junegunn/fzf@latest # Not supported
  - github.com/sclevine/yj@latest
  - github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  - github.com/opentofu/opentofu/cmd/tofu@latest
  - -tags extended github.com/gohugoio/hugo@latest

common_git_repos:
  - url: https://github.com/alacritty/alacritty.git
    prefix: &prefix_home_src "{{ ansible_env.HOME }}/src"
  - url: https://github.com/evgnomon/blueprint.git
    prefix: *prefix_home_src
  - url: https://github.com/evgnomon/zygote.git
    prefix: *prefix_home_src
