---
- name: Download Mullvad keyring
  get_url:
    url: https://repository.mullvad.net/deb/mullvad-keyring.asc
    dest: /usr/share/keyrings/mullvad-keyring.asc
    mode: '0644'
  become: true
  when: ansible_os_family == "Debian"

- name: Add Mullvad repository to apt sources
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch={{ ansible_architecture }}] https://repository.mullvad.net/deb/stable stable main"
    state: present
    filename: mullvad
  become: true
  when: ansible_os_family == "Debian"

- name: Update apt cache after adding Mullvad repository
  apt:
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"