---
galaxy_info:
  author: evgnomon
  description: Installs the .NET SDK and symlinks the dotnet executable
  company:
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all

dependencies:
  - local_bin
