---
galaxy_info:
  author: evgnomon
  description: Ensures Zig Language Server (zls) is built and installed
  company:
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - development
    - zig
    - language-server

dependencies: []