user_fonts_dir: ~/Library/Fonts/ 
fish_bin_prefix: "{{ ansible_env.HOME }}/.macports/bin"
cargo_cmd: "{{ ansible_env.HOME }}/.cargo/bin/cargo"

macports_packages:
 - fish
 - nnn
 - alacritty
 - rsync
 - ctags
 - hugo
 - gnupg2
 - pinentry-mac # this requires XCode

cargo_packages:
  - alacritty
