---
user_fonts_dir: ~/Library/Fonts/
fish_bin_prefix: "{{ ansible_env.HOME }}/.macports/bin"
cargo_cmd: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
pinentry_bin: "{{ macports_home }}/bin/pinentry-tty"

macports_packages:
  - fish
  - nnn
  - alacritty
  - rsync
  - ctags
  - hugo
  - gnupg2
  # This requires XCode
  - pinentry-mac
  - tree
  - the_silver_searcher
  - podman

cargo_packages:
  - alacritty
