- name: Gather OS specific Vars
  hosts: localhost
  gather_facts: true
  tasks:
    - include_tasks: "tasks/setup_vars.yaml"

- name: azure_cli role for Ubuntu
  hosts: localhost
  roles:
    - role: azure_cli
  environment:
    PATH: "{{ custom_path }}"
