---
- name: Install packages for Debian family
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Filter packages based on OS compatibility and WSL support
      include_tasks: roles/charts/tasks/filter_packages.yaml

    - name: Include pkg role
      with_items: "{{ compatible_packages }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg

    - name: Include pkg role for Debian
      with_items: "{{ pkg_debian.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg

- name: Localhost roles for Debian family
  gather_facts: false
  hosts: localhost
  roles:
    - mysql_apt_repo
    - mullvad_apt_repo
    - terminal
    - docker
    - remove-gnome-packages
  environment:
    PATH: "{{ custom_path }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.pyenv/versions/3.12.0/lib/"
