---
- name: Install packages for MacOSX
  hosts: localhost
  tasks:
    - name: Include PKG role for all packages
      with_items: "{{ pkg.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg
      when:
        - ansible_os_family in pkg_versions.get(package.name, {}).get('os_families', [ansible_os_family])

    - name: Include PKG roles for MacOSX specific packages
      with_items: "{{ pkg_mac.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg
      when:
        - ansible_os_family in pkg_versions.get(package.name, {}).get('os_families', [ansible_os_family])

- name: Install DMG packages
  hosts: localhost
  tasks:
    - name: Include DMG role
      with_items: "{{ dmg.charts }}"
      include_role:
        name: dmg
      loop_control:
        loop_var: package
      tags:
        - dmg

- name: localhost roles for MacOSX
  hosts: localhost
  roles:
    - macports
    - terminal
    - tmux
    - python
    - docker
    - dotnet
  environment:
    PATH: "{{ custom_path }}"
    MACPORTS_HOME: "{{ macports_home }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.pyenv/versions/3.12.0/lib/"
