- name: localhost roles for MacOSX
  hosts: localhost
  tasks:
    - name: Include pkg role
      with_items: "{{ pkg.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
  roles:
    - macports
    - terminal
    - vim
    - role: go
    - azure_cli
  environment:
    PATH: "{{ custom_path }}"
    MACPORTS_HOME: "{{ macports_home }}"
