---
- name: Install packages for Ubuntu in server
  hosts: localhost
  tasks:
    - name: Include pkg role
      with_items: "{{ pkg.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package

- name: localhost roles for Ubuntu in server
  hosts: localhost
  roles:
    - terminal
    - vim
  environment:
    PATH: "{{ custom_path }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.pyenv/versions/3.12.0/lib/"
