- name: Install Alacritty
  gather_facts: no
  hosts:
    - all
  roles:
    - alacritty
  tags:
    - alacritty

- name: Install Pip packages
  gather_facts: no
  hosts: all
  vars:
    become_flag: "{{ ansible_os_family == 'Windows' }}"
  become: "{{ become_flag }}"
  roles:
    - python
  tags:
    - pip

- name: Install Eget packages
  gather_facts: no
  hosts: all
  roles:
    - eget
  tags:
    - eget

- name: Install Ruby packages
  gather_facts: no
  hosts: all
  roles:
    - ruby
  tags:
    - ruby

- name: vim role
  hosts: all
  strategy: free
  gather_facts: no
  roles:
    - vim
  tags:
    - vim
  environment:
    PATH: "{{ custom_path }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.pyenv/versions/3.12.0/lib/"
