---
- name: Set variables
  hosts: all
  gather_facts: true
  tasks:
    - name: Read Blueprint config file
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ blueprint_config_file }}"
    - name: Resolve Windows hostname
      ansible.windows.win_command:
        cmd: hostname
      register: result
      when: ansible_os_family == "Windows"
    - name: Set fact for blueprint user
      set_fact:
        blueprint_host_name: "{{ result.stdout | trim }}"
        blueprint_user_home: "{{ win_user[(result.stdout | trim)].home }}"
        blueprint_user:  "{{ win_user[(result.stdout | trim)].user }}"
      when: ansible_os_family == "Windows"
    - name: Include setup variables
      include_tasks: "tasks/setup_vars.yaml"
  tags:
    - always

- name: import playboook for Debian family
  import_playbook: main-Debian.yml
  when: ansible_os_family == "Debian"

- name: Import playboook for Darwin
  import_playbook: main-Darwin.yml
  when: ansible_os_family == "Darwin"

- name: Import playboook for Windows
  import_playbook: main-Windows.yml
  when: ansible_os_family == "Windows"

- name: Import playbook for all platforms
  import_playbook: main-all.yml
