---
- name: Install packages for MacOSX
  hosts: localhost
  tasks:
    - name: Include PKG role
      with_items: "{{ pkg.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg

    - name: Include PKG roles for MacOSX
      with_items: "{{ pkg_mac.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg

- name: Install DMG packages
  hosts: localhost
  tasks:
    - name: Include DMG role
      with_items: "{{ dmg.charts }}"
      include_role:
        name: dmg
      loop_control:
        loop_var: package
      tags:
        - dmg

- name: localhost roles for MacOSX
  hosts: localhost
  roles:
    - macports
    - terminal
    - python
    - vim
    - docker
  environment:
    PATH: "{{ custom_path }}"
    MACPORTS_HOME: "{{ macports_home }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.pyenv/versions/3.12.0/lib/"
