---
- name: Include Charts
  hosts: all
  gather_facts: yes
  roles:
    - charts
  tags:
    - always

- name: import playboook for Debian family
  import_playbook: main-Debian.yml
  when: ansible_os_family == "Debian"

- name: Import playboook for Darwin
  import_playbook: main-Darwin.yml
  when: ansible_os_family == "Darwin"

- name: Import playboook for Windows
  import_playbook: main-Windows.yml
  when: ansible_os_family == "Windows"

- name: Import playbook for all platforms
  import_playbook: main-all.yml
