---
- name: Set variables
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Include setup variables
      include_tasks: "tasks/setup_vars.yaml"
  tags:
    - always

- name: import playboook for Debian family
  import_playbook: main-Debian.yml
  when: ansible_os_family == "Debian"

- name: Import playboook for MacOSX
  import_playbook: main-MacOSX.yml
  when: ansible_distribution == "MacOSX"

- name: Import playboook for Ubuntu on server
  import_playbook: main-Ubuntu-server.yml
  when:
    - ansible_distribution == "Ubuntu"
    - server_runner
