---
- name: Install packages for Debian family
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include pkg role for all packages
      with_items: "{{ pkg.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg
      when:
        - ansible_os_family in pkg_versions.get(package.name, {}).get('os_families', [ansible_os_family])
        - pkg_versions.get(package.name, {}).get('wsl', true) or not wsl2_kernel | default(false)         

    - name: Include pkg role for Debian specific packages
      with_items: "{{ pkg_debian.charts }}"
      when:
        - ansible_os_family in pkg_versions.get(package.name, {}).get('os_families', [ansible_os_family])
        - pkg_versions.get(package.name, {}).get('wsl', true) or not wsl2_kernel | default(false)

      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg

- name: Localhost roles for Debian family
  gather_facts: false
  hosts: localhost
  roles:
    - terminal
    - docker
    - remove-gnome-packages
  environment:
    PATH: "{{ custom_path }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.pyenv/versions/3.12.0/lib/"
