- name: Install Alacritty
  gather_facts: no
  hosts:
    - all
  roles:
    - alacritty
  tags:
    - alacritty

- name: Install Pip packages
  gather_facts: no
  hosts: all
  vars:
    become_flag: "{{ ansible_os_family == 'Windows' }}"
  become: "{{ become_flag }}"
  roles:
    - python
  tags:
    - pip

- name: Install Eget packages
  gather_facts: no
  hosts: all
  roles:
    - eget
  tags:
    - eget
