- name: Gather OS specific Vars
  hosts: localhost
  gather_facts: true
  tasks:
    - include_tasks: "tasks/setup_vars.yaml"

- name: Import playboook for Ubuntu
  import_playbook: main-Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Import playboook for MacOSX
  import_playbook: main-MacOSX.yml
  when: ansible_distribution == "MacOSX"

- name: Import playboook for Ubuntu on server
  import_playbook: main-Ubuntu-server.yml
  when:
    - ansible_distribution == "Ubuntu"
    - server_runner
