---
- name: Install packages for Debian family
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Include pkg role
      with_items: "{{ pkg.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg

    - name: Include pkg role for Debian
      with_items: "{{ pkg_debian.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
      tags:
        - pkg

- name: Localhost roles for Debian family
  gather_facts: no
  hosts: localhost
  roles:
    - terminal
    - docker
  environment:
    PATH: "{{ custom_path }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.pyenv/versions/3.12.0/lib/"
