- name: Install Alacritty
  gather_facts: false
  hosts:
    - all
    - localhost
  roles:
    - alacritty
  tags:
    - alacritty

- name: Install Pip packages
  gather_facts: false
  hosts:
    - all
    - localhost    
  vars:
    become_flag: "{{ ansible_os_family == 'Windows' }}"
  become: "{{ become_flag }}"
  roles:
    - python

- name: Install Eget packages
  gather_facts: false
  hosts: 
    - all
    - localhost
  roles:
    - eget
  tags:
    - eget

- name: Install Ruby packages
  gather_facts: false
  hosts: 
    - all
    - localhost
  roles:
    - ruby
  tags:
    - ruby

- name: Install Rust packages
  gather_facts: false
  hosts: 
    - all
    - localhost
  roles:
    - ensure_rust
  tags:
    - rust

- name: Install C# Language Server
  gather_facts: false
  hosts: 
    - all
    - localhost
  roles:
    - ensure_csharp_ls
  tags:
    - cs

- name: vim role
  hosts: 
    - all
    - localhost
  strategy: free
  gather_facts: false
  roles:
    - vim
  tags:
    - vim
  environment:
    PATH: "{{ custom_path }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.pyenv/versions/3.12.0/lib/"
