---
- name: Set variables
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Include setup variables
      include_tasks: "tasks/setup_vars.yaml"
  tags:
    - always

- name: Add Package role
  hosts: localhost
  tasks:
    - name: Include pkg role
      with_items: "{{ pkg.charts }}"
      include_role:
        name: pkg
      loop_control:
        loop_var: package
  environment:
    PATH: "{{ custom_path }}"
