---
- name: Include Charts
  hosts: all
  gather_facts: no
  roles:
    - charts
  tags:
    - always

- name: Update GitHub secrets
  hosts: localhost
  roles:
    - name: github_secret
      vars:
        secrets: "{{ secrets }}"
