[lint]
select = ["ALL"]
ignore = [
  "BLE001",
  "D100",
  "D101",
  "D103",
  "D203",
  "D212",
  "D213",
  "EM101",
  "EM102",
  "FA102",
  "I001",
  "S603",
  "S607",
  "T201",
  "TRY002",
  "TRY003",
  # "E501",
  # "F401", 
  # "S113",
  # "UP015",
]
