- name: Set OS specific Vars
  hosts: localhost
  gather_facts: true
  tasks:
    - include_tasks: "tasks/setup_vars.yaml"

- name: Zygote role
  hosts: localhost
  roles:
    - role: terminal
  environment:
    PATH: "{{ custom_path }}"
