---
dotfiles:
  - .config/containers/containers.conf
  - .config/containers/registries.conf
  - .config/hcloud/cli.sh
  - .gitignore_global
  - .gitconfig
  - .ctags
  - .cargo/config.toml
  - .gnupg/gpg.conf
  - .gnupg/scdaemon.conf
  - .eget.toml
  - .ctags.d/javascript.ctags
  - .bashrc
  - .inputrc
  - .profile
  - .bash_aliases
