---
- name: Read Blueprint config file
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ blueprint_config_file }}"

- name: Check running in the server
  set_fact:
    server_runner: "{{ ansible_kernel | split('-') | last == 'WSL2' }}"

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family}}.yml"
  when: not server_runner

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-server.yml"
    - "vars/{{ ansible_distribution }}-server.yml"
    - "vars/{{ ansible_os_family}}-server.yml"
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family}}.yml"
  when: server_runner

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/pkg_charts.yaml"
