---
- name: Read Blueprint config file
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ blueprint_config_file }}"

- name: Check running in the server
  set_fact:
    wsl2_kernel: "{{ ansible_kernel | split('-') | last == 'WSL2' }}"

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family}}.yml"
  when: not wsl2_kernel 

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-server.yml"
    - "vars/{{ ansible_distribution }}-server.yml"
    - "vars/{{ ansible_os_family}}-server.yml"
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family}}.yml"
  when: wsl2_kernel

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/pkg_versions.yaml"

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/pkg_charts.yaml"

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/pkg_charts_mac.yaml"
  when: ansible_os_family == 'Darwin'

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/pkg_charts_debian.yaml"
  when: ansible_os_family == 'Debian'

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/dmg_charts.yaml"
  when: ansible_os_family == 'Darwin'
