- name: Create destination directory
  file:
    path: "{{ path }}"
    state: directory
  with_items:
    - "{{ package_dest }}"
  loop_control:
    loop_var: path


- name: Create source directory for package
  file:
    path: "{{ path | dirname }}"
    state: directory
  with_items:
    - "{{ package_src }}"
  loop_control:
    loop_var: path

- name: Download package
  command:
    cmd: |
      curl --proto '=https' --tlsv1.2 -sSLf {{ package.template.url | format( version = package.version, name = package.name ) }} -o '{{ package_src }}'
    creates: "{{ package_src }}"

- name: Inflate package
  shell: |
      {{ package.template.inflate | format( src =  package_src, dest = package_dest, name = package.name) }}
  args:
    creates: "{{ package_dest }}/{{ package.template.creates }}"
