---
blueprint_user_home: "{{ ansible_env.HOME }}"
blueprint_home: "{{ blueprint_user_home }}/.cache/blueprint"
path_components:
  - "{{ blueprint_user_home }}/go/bin"
  - "{{ blueprint_user_home }}/.cargo/bin"
  - "{{ blueprint_user_home }}/.local/bin"
  - "{{ blueprint_user_home }}/.pyenv/shims"
  - "{{ blueprint_user_home }}/.rbenv/shims"
  - "{{ blueprint_user_home }}/.gem/bin"
  - "/usr/local/bin"
  - "/usr/bin"
custom_path: "{{ path_components | join(':') }}:$PATH"

cargo_packages:
