- name: Gather OS specific Vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family}}.yml"

- file:
    path: "{{ ansible_env.HOME }}/opt/node-{{ nodejs_version }}"
    state: directory
    mode: 0755

- file:
    path: "{{ blueprint_home }}/node"
    state: directory
    mode: 0755

- get_url: 
    url: https://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}-{{ nodejs_os_type }}-x64.tar.gz
    dest: "{{ blueprint_home }}/node/node-{{ nodejs_version }}-{{ nodejs_os_type }}-x64.tar.gz"
    # checksum: sha256:fc5b73f2a78c17bbe926cdb1447d652f9f094c79582f1be6471b4b38a2e1ccc8

- name: UnTar archive
  command:
    cmd: tar -xzvf "{{ blueprint_home }}/node/node-{{ nodejs_version }}-{{ nodejs_os_type }}-x64.tar.gz" -C "{{ ansible_env.HOME }}/opt/node-{{ nodejs_version }}"
    creates: "{{ ansible_env.HOME }}/opt/node-{{ nodejs_version }}/node-{{ nodejs_version }}-{{ nodejs_os_type }}-{{ nodejs_os_arch }}"

- name: Set fish/conf.d/nodejs.fish
  template:
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/nodejs.fish"
    src: nodejs.fish.j2 
