---
- name: Check if csharp-ls is already installed
  command: "{{ ansible_env.HOME }}/.dotnet/tools/csharp-ls --version"
  register: csharp_ls_check
  changed_when: false
  failed_when: false

- name: Install csharp-ls using dotnet tool
  command: dotnet tool install --global csharp-ls
  when: csharp_ls_check.rc != 0

- name: Verify csharp-ls installation
  command: "{{ ansible_env.HOME }}/.dotnet/tools/csharp-ls --version"
  register: csharp_ls_version
  changed_when: false

- name: Display csharp-ls version
  debug:
    msg: "csharp-ls version: {{ csharp_ls_version.stdout }}"
