---
- name: Install Ruby using Rbenv
  shell: |
    unset SDKROOT
    rbenv install {{ pkg_versions.ruby.version }}
  register: ruby_install
  failed_when:
    - ruby_install.rc != 0
    - not "already exists" in ruby_install.stderr
  changed_when:
    - ruby_install.rc == 0
  tags:
    - ruby

- name: Set global ruby version
  shell: rbenv global {{ pkg_versions.ruby.version }}
  tags:
    - ruby

- name: Install Gems
  shell: |
    unset SDKROOT
    gem install {{ item }}
  with_items: "{{ common_gem_packages }}"
  tags:
    - ruby
    - gem
