---
- command: python -m pip install {{ common_pip_packages | join(' ') }}
  tags:
    - pip
  when:
    - no_upgrade is defined
    - no_upgrade | bool
  name: Install common pip packages

- command: python -m pipx install {{ common_pipx_packages | join(' ') }}
  when:
    - no_upgrade is defined
    - no_upgrade | bool
  tags:
    - pip
  name: Install common pipx packages

- command: python -m pip install --upgrade {{ common_pip_packages | join(' ') }}
  when: >
    no_upgrade is not defined or
    (no_upgrade is defined and not (no_upgrade | bool))
  tags:
    - pip
  name: Upgrade common pip packages

- command: python -m pipx upgrade {{ common_pipx_packages | join(' ') }}
  when: >
    no_upgrade is not defined or
    (no_upgrade is defined and not (no_upgrade | bool))
  tags:
    - pip
  name: Upgrade common pipx packages
