---
package_src: "{{ blueprint_home }}/{{ package.name }}/{{ package.template.os }}_{{ package.template.arch }}/{{ package.name }}_{{ package.version }}.{{ package.template.ext | default('bin') }}"
package_dest: "{{ blueprint_home }}/{{ package.name }}/{{ package.template.os }}_{{ package.template.arch }}/{{ package.name }}_{{ package.version }}"
