- include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "vars/{{ ansible_distribution }}.yaml"
    - "vars/{{ ansible_os_family}}.yaml"

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/main.yaml"
