package_dir: "{{ blueprint_home }}/{{ package.name }}/{{ package.template.os }}_{{ package.template.arch }}"
package_src: "{{ package_dir }}/{{ package.name }}_{{ package.version }}.{{ package.template.ext | default('dmg') }}"
mount_point: "/Volumes/{{ package.name }}-{{ package.version }}"
