---
- name: Check running in the server (for WSL detection)
  set_fact:
    wsl2_kernel: "{{ ansible_kernel | split('-') | last == 'WSL2' }}"

- name: Create final filtered list based on architecture compatibility
  set_fact:
    compatible_packages: []

- name: Check package compatibility
  set_fact:
    compatible_packages: "{{ compatible_packages + [item] }}"
  with_items: "{{ pkg.charts }}"
  when:
    - item.name in pkg_versions
    - ansible_os_family in pkg_versions[item.name].get('os_families', [ansible_os_family])
    - (not wsl2_kernel) or pkg_versions[item.name].get('wsl', true)
    - item.get('archs', []) | selectattr('architecture', 'equalto', ansible_architecture) | selectattr('os_family', 'equalto', ansible_os_family) | list | length > 0 or item.get('archs') is none