- name: Create /etc/apt/keyrings directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and add Microsoft GPG key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc

- name: Import Microsoft GPG key
  become: true
  ansible.builtin.apt_key:
    file: /tmp/microsoft.asc
    keyring: /etc/apt/keyrings/microsoft.gpg

- name: Set permissions for Microsoft GPG key
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/microsoft.gpg
    mode: '0644'

- name: Get distribution code name
  ansible.builtin.command:
    cmd: lsb_release -cs
  register: distro_codename

- name: Get architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: architecture

- name: Add Azure CLI repository
  become: true
  ansible.builtin.template:
    src: azure-cli.list.j2
    dest: /etc/apt/sources.list.d/azure-cli.list
    owner: root
    group: root
    mode: '0644'

- name: Install azure-cli using Apt
  # become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - azure-cli
    state: present
