- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family}}.yml"

- file:
    path: "{{ go_home }}"
    state: directory
    mode: 0755

- file:
    path: "{{ go_cache }}"
    state: directory
    mode: 0755

- get_url: 
    url: https://go.dev/dl/go{{ go_version }}.{{ go_os_type }}-{{ go_os_arch }}.tar.gz
    dest: "{{ go_bundle }}"

- name: untar archive
  command:
    cmd: tar -xzvf "{{ go_bundle }}" -C "{{ go_home }}"

- name: Set fish/conf.d/go.fish
  template:
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/go.fish"
    src: go.fish.j2 

- name: Install Go modules
  shell: |
    {{ go_home }}/go/bin/go install {{ item }}
  loop: "{{ go_install }}"
