ghostty_repo: "{{ ansible_facts['env']['HOME'] }}/src/github.com/ghostty-org/ghostty"
ghostty_bin_output: "{{ ghostty_repo }}/zig-out/bin/ghostty"
ghostty_bin: "{{ local_bin_path }}/ghostty"
zig_compiler: "zig14"
