---
- file:
    state: directory
    path: "{{ target }}/{{ item.path | replace('.j2', '') | dirname }}"
  become: "{{ target == '/etc' }}"
  tags:
    - always

- template:
    src: "{{ item.src }}"
    dest: "{{ target }}/{{ item.path | replace('.j2', '') }}"
  become: "{{ target == '/etc' }}"
  when:
    - item.path[-3:] == '.j2'
  tags:
    - always

- copy:
    src: "{{ item.src }}"
    dest: "{{ target }}/{{ item.path }}"
  become: "{{ target == '/etc' }}"
  when:
    - item.path[-3:] != '.j2'
  tags:
    - always
