---
- file:
    state: directory
    path: "/tmp/mk/{{ item.path | replace('.j2', '') | dirname }}"
- template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path | replace('.j2', '') }}"
