---
- file:
    state: directory
    path: "{{ target }}/{{ item.path | replace('.j2', '') | dirname }}"
  become: "{{ become | default(false) }}"
  tags:
    - always
- template:
    src: "{{ item.src }}"
    dest: "{{ target }}/{{ item.path | replace('.j2', '') }}"
  become: true
  tags:
    - always
