---
galaxy_info:
  author: evgnomon
  description: Ensures Rust and rust-analyzer are installed
  company:
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - development
    - rust
    - language-server

dependencies: []
