- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found: &archs-ansible-files
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family}}.yaml"
  tags:
    - always

- name: Include Docker tasks
  include_tasks: "{{ item }}"
  with_first_found: *archs-ansible-files
  tags:
    - always
