---
- name: Checkout vim repo
  git:
    dest: "{{ ansible_env.HOME }}/src/github.com/vim/vim"
    repo: "https://github.com/vim/vim.git"
  tags:
    - vim

- name: Install vim
  script: install-{{ ansible_os_family }}.fish
  args:
    chdir: "{{ ansible_env.HOME }}/src/github.com/vim/vim"
    executable: "fish"
  tags:
    - vim

- name: Install vim plug
  shell: curl -fLo {{ ansible_env.HOME }}/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
  tags:
    - vim

- name: Copy Vim config files
  synchronize:
    src: "{{ item }}"
    dest: "{{ blueprint_user_home }}"
  loop:
    - .vimrc
    - .ideavimrc
    - coc-settings.json
  tags:
    - dotfiles
    - vim
