---
- name: Checkout vim repo
  git:
    dest: "{{ ansible_env.HOME }}/src/github.com/vim/vim"
    repo: "https://github.com/vim/vim.git"

- name: Install vim
  script: install-{{ ansible_distribution }}.fish
  args:
    chdir: "{{ ansible_env.HOME }}/src/github.com/vim/vim"
    executable: "fish"

- name: Install vim plug
  shell: curl -fLo {{ ansible_env.HOME }}/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"

- name: Copy .vimrc
  synchronize:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}"
  loop:
    - .vimrc
