---
- include_role:
    name: host_vars

- name: Create ansible directory
  win_file:
    path: "{{ alacritty_config_dir }}"
    state: directory
  when: ansible_os_family == "Windows"

- name: Create ansible directory
  file:
    path: "{{ alacritty_config_dir }}"
    state: directory
  when: ansible_os_family != "Windows"

- template:
    src: templates/alacritty.toml.j2
    dest: "{{ alacritty_config_file }}"
  vars:
    wsl_user_home: "/home/{{ ansible_env.USER }}"

- shell: |
    mkdir -p ~/.config/alacritty/themes
    git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
  args:
    creates: ~/.config/alacritty/themes
